### ISSUE TITLE
Address[] can not assign to Bytes[]

### ISSUE THREAD

**Issue by sdakhara** [graphprotocol/graph-cli#1017]
I don't know what went wrong but when i try `npm run build`  which runs `graph build` it throws error mentioned bellow
```
Compile subgraphERROR TS2322: Type '~lib/array/Array<~lib/@graphprotocol/graph-ts/common/numbers/Address>' is not assignable to type '~lib/array/Array<~lib/@graphprotocol/graph-ts/common/collections/Bytes>'.

   entity.targets = event.params.targets;
                    ~~~~~~~~~~~~~~~~~~~~
 in src/dcode-dao.ts(43,20)

✖ Failed to compile subgraph: Failed to compile data source mapping: 1 compile error(s)
Error: Failed to compile data source mapping: 1 compile error(s)
    at Compiler._compileDataSourceMapping (/home/eu4/Desktop/DcodeGraph/node_modules/@graphprotocol/graph-cli/src/compiler/index.js:320:13)
    at /home/eu4/Desktop/DcodeGraph/node_modules/@graphprotocol/graph-cli/src/compiler/index.js:224:20
    at updateInDeepMap (/home/eu4/Desktop/DcodeGraph/node_modules/immutable/dist/immutable.js:1971:22)
    at updateInDeepMap (/home/eu4/Desktop/DcodeGraph/node_modules/immutable/dist/immutable.js:1980:23)
    at updateInDeepMap (/home/eu4/Desktop/DcodeGraph/node_modules/immutable/dist/immutable.js:1980:23)
    at Map.updateIn (/home/eu4/Desktop/DcodeGraph/node_modules/immutable/dist/immutable.js:1278:26)
    at /home/eu4/Desktop/DcodeGraph/node_modules/@graphprotocol/graph-cli/src/compiler/index.js:223:24
    at /home/eu4/Desktop/DcodeGraph/node_modules/immutable/dist/immutable.js:3016:46
    at List.__iterate (/home/eu4/Desktop/DcodeGraph/node_modules/immutable/dist/immutable.js:2206:13)
    at IndexedIterable.mappedSequence.__iterateUncached (/home/eu4/Desktop/DcodeGraph/node_modules/immutable/dist/immutable.js:3015:23)
UNCAUGHT EXCEPTION: Error: The AssemblyScript compiler crashed when compiling this file: 'src/dcode-dao.ts'
Suggestion: try to comment the whole file and uncomment it little by little while re-running the graph-cli until you isolate the line where the problem happens.
Also, please contact us so we can make the CLI better by handling errors like this. You can reach out in any of these links:
- Discord channel: https://discord.gg/eM8CA6WA9r
- Github issues: https://github.com/graphprotocol/graph-cli/issues
```

I was creating a DAO contract using Openzeppelin Governor contract and this contract emits an event called 
```
ProposalCreated (uint256 proposalId, address proposer, address[] targets, uint256[] values, string[] signatures, bytes[] calldatas, uint256 startBlock, uint256 endBlock, string description)
```

You can see that it emits an Address array named targets. when i run `npm run codegen` it create this parameter as an Address Array type object. and in side the build script it assigns to a Bytes Array type Object.

and it throws the error. 
```
ERROR TS2322: Type '~lib/array/Array<~lib/@graphprotocol/graph-ts/common/numbers/Address>' is not assignable to type '~lib/array/Array<~lib/@graphprotocol/graph-ts/common/collections/Bytes>'.

   entity.targets = event.params.targets;
                    ~~~~~~~~~~~~~~~~~~~~
 in src/dcode-dao.ts(43,20)
```
i have mentioned whole error console on top of the issue.

inshort 
Address Array can not be Assigned to the Bytes Array.

Tell me if you need any screen shot of the error.

**Comment by pablote** [comment]
I've just run into this issue, it's fairly easy to reproduce. Just have a contract with an event, with one of it's args being a `address[]`. This causes `graph init` to generate the following Graphql code: 

```
...
owners: [Bytes]! # address[]
...
```

Graphql doesn't seem to like this:
```
GraphQL schema can't have List's with Nullable members.
Error in 'owners' field of type '[Bytes]'.
Suggestion: add an '!' to the member type of the List, change from '[Bytes]' to '[Bytes!]'
```
The solution, as suggested by the error message, is to change that line to:

```
owners: [Bytes!]! # address[]
```

The problem with this is that, since this fails during the `graph init` command, now I don't know if that did all it needed to do, or if there were some steps skipped because of the error. The fix should just be to generate the correct Graphql types.

**Comment by sdakhara** [comment]
I have also tried to do exactly what CLI told
after changing the owners: [Bytes]! # address[] to owners: [Bytes!]! # address[] the graph codegen command worked compeletly fine but
when I run the build command it shows me the error that I mentioned in my issue https://github.com/graphprotocol/graph-cli/issues/1017

and i have did some digging and changed the type in ts file which is used for build

entity.targets = changetype<Bytes[]>(event.params.targets)

here the event.params.targets is an Address[] and entity.targets is a Bytes[]
so i have changed it's type with changetype<Bytes[]>.

i don't know if this is a good fix or not but it worked.

**Comment by sekaieth** [comment]
I can confirm the same issue; I replaced Address[] with Bytes[] and it all works, but would be nice to have this fixed long-term.

**Comment by pablote** [comment]
I found a closed issue mentioning that you could do the following, this works for me:

```
entity.owners = Value.fromAddressArray(event.params.owners).toBytesArray();
```

Reference: https://github.com/graphprotocol/graph-cli/issues/1017, I wish the codegen would just do this out of the box.

**Comment by Brentably** [comment]
Yeah, this is kind of funny. I'm glad this ticket is open though so I don't have to make one.

**Comment by sdakhara** [comment]
> > here the event.params.targets is an Address[] and entity.targets is a Bytes[] so i have changed it's type with changetype<Bytes[]>.
> > i don't know if this is a good fix or not but it worked.
> 
> what is changetype<> ? can't find anything about it on google. having a similar issue @sdakhara

I was looking inside of the Generated Files of the Graph which were created when I ran `graph codegen` 
and found this function called `changetype<>` and i followed this function and it took me to the Assembly Script module in node_modules 
that's where this function is coming from.
