### ISSUE TITLE
Conversion from 'AssemblyScript' to 'Value' for source type 'EthereumTuple' is not supported

### ISSUE THREAD

**Issue by brockelmore** [graphprotocol/graph-cli#253]
When trying load in an ABI local file for a deployed contract, I get the following error:

```
Error: Conversion from 'AssemblyScript' to 'Value' for source type 'EthereumTuple' is not supported
    at findConversionFromType (/Users/brockelmore/.nvm/versions/node/v8.12.0/lib/node_modules/@graphprotocol/graph-cli/src/codegen/types/index.js:42:11)
    at valueTypeForAsc (/Users/brockelmore/.nvm/versions/node/v8.12.0/lib/node_modules/@graphprotocol/graph-cli/src/codegen/types/index.js:96:3)
    at ethereumTypeToGraphQL (/Users/brockelmore/.nvm/versions/node/v8.12.0/lib/node_modules/@graphprotocol/graph-cli/src/scaffold.js:89:10)
    at event.inputs.map (/Users/brockelmore/.nvm/versions/node/v8.12.0/lib/node_modules/@graphprotocol/graph-cli/src/scaffold.js:97:50)
    at Array.map (<anonymous>)
    at generateEventType (/Users/brockelmore/.nvm/versions/node/v8.12.0/lib/node_modules/@graphprotocol/graph-cli/src/scaffold.js:95:10)
    at Array.map (<anonymous>)
    at generateSchema (/Users/brockelmore/.nvm/versions/node/v8.12.0/lib/node_modules/@graphprotocol/graph-cli/src/scaffold.js:107:8)
    at generateScaffold (/Users/brockelmore/.nvm/versions/node/v8.12.0/lib/node_modules/@graphprotocol/graph-cli/src/scaffold.js:152:16)
    at withSpinner (/Users/brockelmore/.nvm/versions/node/v8.12.0/lib/node_modules/@graphprotocol/graph-cli/src/commands/init.js:529:28)
```

**Comment by Jannis** [comment]
@brockelmore Good catch, I know what the problem is:

We do not support struct/tuple fields in the subgraph schema yet but if `--from-contract` sees an ABI that includes a tuple event parameter, it tries to create an event entity type with a struct/tuple field for that parameter.

We have a few options here, some more useful, some less:

1. Represent the type as a byte array. This would require the ability to encode structs in mappings, which isn't hard to do. It wouldn't be super useful from a user's perspective though.

2. Represent the struct/tuple as an inline object. This would require allowing non-entity object types in the schema (one for each struct) and supporting these in entity fields. This would be the most useful approach. It would require changes across the board (the tricky parts being the GraphQL execution that'll need to distinguish between inline objects and entity objects, as well as the AssemblyScript deserialization.). Should be doable though.

We'll look into it.

**Comment by brockelmore** [comment]
Awesome, glad I could point this out

**Comment by Jannis** [comment]
There is a third option:

For any event parameter that is a struct, generate GraphQL fields like
```graphql
type EventName @entity {
  paramName_structFieldName: BigInt!
  paramName_structFieldName_innerStructFieldName: Bytes!
}
```
So basically map any struct field like `paramName.structFieldName` to `paramName_structFieldName`, while also supporting nested structs.

This could be a decent solution for now; a longer term solution would be inline objects.

**Comment by mudgen** [comment]
Are there any plans to support Solidity structs directly?
