### ISSUE TITLE
Doens't work with yarn workspaces

### ISSUE THREAD

**Issue by PaulRBerg** [graphprotocol/graph-cli#258]
## Description
I followed the [tutorial][tutorial] and I made it work with the example subgraph, but I encountered the following error when I switched to a monorepo maintained with lerna + yarn workspaces:

```
Failed to compile subgraph: Failed to compile data source mapping: Import file '~lib/@graphprotocol/graph-ts.ts' not found.
```

Of course, I made sure I have all the dependencies installed and I confirmed by that by looking into the node_modules folder at the root of the repo. I suspect that's actually why the CLI tool is complaining: it can't resolve higher-up node_modules!

## EthereumTupple Error

I tried to manually copy over the libraries:

```bash
cp -R ../../node_modules/@graphprotocol ./node_modules/@graphprotocol
```

That indeed changed the output, but I got this:

```
ERROR TS2305: Module '~lib/@graphprotocol/graph-ts' has no exported member 'EthereumTuple'.

   EthereumTuple,
   ~~~~~~~~~~~~~
in src/types/Sablier/Sablier.ts(8,2)

ERROR TS2377: Constructors for derived classes must contain a 'super' call.

export class Entity extends TypedMap<string, Value> {
  constructor() {
    this.entries = new Array<TypedMapEntry<string, Value>>(0)
}
                                                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 in ~lib/@graphprotocol/graph-ts/index.ts(810,53)
```

I know about:

- https://github.com/graphprotocol/graph-cli/issues/257
- https://github.com/graphprotocol/graph-node/issues/766

But I'm not using the ABIEncoderV2 so I don't think this should fail. I am, though, instantiating structs in my [contract][streams-contract]'s constructor.

## Environment

- macOS
- yarn 1.15.2
- @graphprotocol/graph-cli 0.10.0
- @graphprotocol/graph-ts 0.6.0

Also tried downgrading the versions but had the exact same issues.

[streams-contract]: https://github.com/SablierApp/monorepo/blob/develop/packages/contracts/contracts/streams/Streams.sol
[tutorial]: https://thegraph.com/docs/quick-start#local-development

**Comment by Jannis** [comment]
Looks like you figured the `EthereumTuple` error in #257 out yourself.

Due to the way the AssemblyScript compiler works, we're using our own logic to look up the `@graphprotocol/graph-ts` module. Support for proper module resolution in the compiler is being tracked here: https://github.com/AssemblyScript/assemblyscript/issues/448.

**Comment by Jannis** [comment]
Having said that, it should be easy to add support for this.

**Comment by PaulRBerg** [comment]
For what it's worth, I just managed to fix this by using [nohoist](https://yarnpkg.com/blog/2018/02/15/nohoist/):

```javascript
// package.json
{
  ...
  "workspaces": {
    "packages": [
      "packages/*"
    ],
    "nohoist": [
      "packages/subgraph/@graphprotocol/graph-ts",
      "packages/subgraph/@graphprotocol/graph-ts/**"
    ]
  }
}
```

**Comment by andrei-anisimov** [comment]
Any update on this? I'm getting the following when trying to have subgraph as a yarn workspace package.

```
Error: Failed to compile data source mapping: Import file '~lib/@graphprotocol/graph-ts.ts' not found.
```

**Comment by piavgh** [comment]
> Any update on this? I'm getting the following when trying to have subgraph as a yarn workspace package.
> 
> ```
> Error: Failed to compile data source mapping: Import file '~lib/@graphprotocol/graph-ts.ts' not found.
> ```

Updating `graph-cli` and `graph-ts` to version `^0.20.0` solves this problem

**Comment by EzeScigo** [comment]
> 
> 
> > Any update on this? I'm getting the following when trying to have subgraph as a yarn workspace package.
> > ```
> > Error: Failed to compile data source mapping: Import file '~lib/@graphprotocol/graph-ts.ts' not found.
> > ```
> 
> Updating `graph-cli` and `graph-ts` to version `^0.20.0` solves this problem

OMG thank you. This solved my problem as well with yarn workspaces

**Comment by AlbertSu123** [comment]
I'm getting a similar issue: 
`Error: Failed to compile data source mapping: Import file '~lib/prettier.ts' not found.`
Tried both idea, didn't work. Does anyone have suggestions?

**Comment by AlbertSu123** [comment]
> I'm getting a similar issue:
> `Error: Failed to compile data source mapping: Import file '~lib/prettier.ts' not found.`
> Tried both ideas, didn't work. Does anyone have suggestions?

My solution was to just uninstall and reinstall everything related to the graph protocol on my computer. That fixed it for me.

**Comment by jjperezaguinaga** [comment]
I'm seeing a similar issue when trying to install an external dependency in Typescript, but not within a workspace project. In my case, I'm importing a Typescript dependency on my `mappings.ts` as follows:

```
import { generateChannelId } from '@hoprnet/hopr-utils/lib/types/channelEntry'
import { Address } from '@hoprnet/hopr-utils/lib/types/primitives'
```
(these are JavaScript compiled files, and I'm fetching directly from the folders but they are also exported [as you can see in the source package](https://github.com/hoprnet/hoprnet/blob/master/packages/utils/src/index.ts))

As a result, I cannot compile the project:

```
gitpod /workspace/hopr-analytics/subgraph-channels $ yarn build
yarn run v1.22.10
$ graph build
  Skip migration: Bump mapping apiVersion from 0.0.1 to 0.0.2
  Skip migration: Bump mapping apiVersion from 0.0.2 to 0.0.3
  Skip migration: Bump mapping apiVersion from 0.0.3 to 0.0.4
  Skip migration: Bump mapping specVersion from 0.0.1 to 0.0.2
✔ Apply migrations
✔ Load subgraph from subgraph.yaml
  Compile data source: HoprChannels => build/HoprChannels/HoprChannels.wasm
✖ Failed to compile subgraph: Failed to compile data source mapping: Import file '~lib/@hoprnet/hopr-utils/lib/types/channelEntry.ts' not found.
Error: Failed to compile data source mapping: Import file '~lib/@hoprnet/hopr-utils/lib/types/channelEntry.ts' not found.
    at Compiler._compileDataSourceMapping (/workspace/hopr-analytics/subgraph-channels/node_modules/@graphprotocol/graph-cli/src/compiler.js:312:13)
    at /workspace/hopr-analytics/subgraph-channels/node_modules/@graphprotocol/graph-cli/src/compiler.js:206:20
```

You can replicate this error in the following [branch](https://github.com/hoprnet/hopr-analytics/blob/jjpa/channels-subgraph/subgraph-channels/src/mapping.ts).

**Comment by schmidsi** [comment]
@jjperezaguinaga as [Jannis commented above](https://github.com/graphprotocol/graph-cli/issues/258#issuecomment-490628891), the import process into AssemblyScript is different and does not follow the same standards as node.js. As far as I know, important is that the source .ts files are deployed to NPM.

That said, there is a library that seems to be importable: [protofire/subgraph-toolkit](https://github.com/protofire/subgraph-toolkit). The only difference that I see currently, is that you do not [expose a `module` field in your `package.json` like they do](https://github.com/protofire/subgraph-toolkit/blob/main/package.json#L8).

**Comment by jjperezaguinaga** [comment]
@schmidsi Thanks for pointing this out! And checked out protofire's subgrapth toolkit, super useful (wouldn't expect anything less from @mgarciap's team!).

We aren't ESM friendly yet, but might be enough time to change that. I will test locally and get back to you, merci!

**Comment by jjperezaguinaga** [comment]
@schmidsi Reporting back as promised. Although I successfully managed to have `graph-cli` process my [updated module](https://www.npmjs.com/package/@hoprnet/hopr-utils/v/1.74.0-next.23-module) (see changes [here](https://github.com/hoprnet/hoprnet/commit/6a7e22a01e5eb1d81cc436370a6e97dda4846620)), the follow-up problem comes from imported libraries that are not ESM friendly and thus [breaking the build](https://github.com/hoprnet/hoprnet/issues/2056#issuecomment-874651242).

Although I can live with that, I started to wonder how many of these libraries are actually supported, or whether `graph-cli` supports at all importing and reusing lives. For instance, [ethers](https://docs.ethers.io/v5/single-page/) can't be imported as a ESM module despite having exporting their `.ts` files, and trying to fetch them as such, will return

![image](https://user-images.githubusercontent.com/1128312/124591631-cf3a6400-de5c-11eb-8853-6ad7a5bec8ec.png)


which will prompt you to include `@ethersproject/bytes/src/index` (as an example), which in turn will follow-up with the dependency tree corresponding errors (here's a [blog post](https://dev.to/asteinarson/typescript-nodejs-and-es6-esm-modules-18ea) documenting this behaviour):

![image](https://user-images.githubusercontent.com/1128312/124591781-fdb83f00-de5c-11eb-9989-f247a0b7101b.png)

Furthermore, I tried with @otaviopace PR #690 as you can see in my [branch](https://github.com/hoprnet/hopr-analytics/blob/jjpa/258-graph-cli/subgraph-channels/package.json#L14) to no avail. I'm not sure how I can import external libraries to parse my contract events, or to be more accurate, to reuse my own typings to avoid recoding logic using the generated types. 

FWIW, I inspected @sistemico 's [subgraph-toolkit](https://github.com/protofire/subgraph-toolkit), and noticed everything was coded from scratch. Even @paulrberg 's [sablier subgraph's](https://github.com/sablierhq/sablier-subgraph/tree/main/src/mappings), @pi0neerpat's [superfluid subgraph's](https://github.com/superfluid-finance/protocol-monorepo/tree/dev/packages/subgraph/src/mappings) and @austingriffith's [scaffold-eth demo subgraph](https://github.com/austintgriffith/scaffold-eth/blob/master/packages/subgraph/src/mapping.ts) relies only on automatically generated schema, so it might be safe to say that for most cases you do not need an external library.

As a conclusion, would it be fair to say that,

- as of today general importing of libraries to process event mappings is not supported, and thus
- the rule of thumb is to leverage on the generated schema tooling to process events data?

For now I'll go ahead and process the events using the in-house tooling. If anyone has a working example of a two-levels depth importing of a CJS compiled library to map events, it would be great.

**Comment by jjperezaguinaga** [comment]
FWIW the [documentation](https://thegraph.com/docs/developer/quick-start#15-can-i-import-ethersjs-or-other-js-libraries-into-my-subgraph-mappings) states that it's indeed not supporting importing other libraries. This is unrelated to the original issue, but might be enough for googlers that find this issue useful.

**Comment by zimmah** [comment]
> @schmidsi Reporting back as promised. Although I successfully managed to have `graph-cli` process my [updated module](https://www.npmjs.com/package/@hoprnet/hopr-utils/v/1.74.0-next.23-module) (see changes [here](https://github.com/hoprnet/hoprnet/commit/6a7e22a01e5eb1d81cc436370a6e97dda4846620)), the follow-up problem comes from imported libraries that are not ESM friendly and thus [breaking the build](https://github.com/hoprnet/hoprnet/issues/2056#issuecomment-874651242).
> 
> Although I can live with that, I started to wonder how many of these libraries are actually supported, or whether `graph-cli` supports at all importing and reusing lives. For instance, [ethers](https://docs.ethers.io/v5/single-page/) can't be imported as a ESM module despite having exporting their `.ts` files, and trying to fetch them as such, will return
> 
> ![image](https://user-images.githubusercontent.com/1128312/124591631-cf3a6400-de5c-11eb-8853-6ad7a5bec8ec.png)
> 
> which will prompt you to include `@ethersproject/bytes/src/index` (as an example), which in turn will follow-up with the dependency tree corresponding errors (here's a [blog post](https://dev.to/asteinarson/typescript-nodejs-and-es6-esm-modules-18ea) documenting this behaviour):
> 
> ![image](https://user-images.githubusercontent.com/1128312/124591781-fdb83f00-de5c-11eb-9989-f247a0b7101b.png)
> 

I am having this problem too but with `@graphprotocol`
