### ISSUE TITLE
"ERROR TS2339: Property 'replace' does not exist on type '~lib/string/String'" when compiling mappings

### ISSUE THREAD

**Issue by andrei-anisimov** [graphprotocol/graph-cli#491]
The following code in mappings causes an error during local deploy. 

code:
```
params.contractName.replace('0x00', '')
```

error:
```
⠋ Compile subgraphERROR TS2339: Property 'replace' does not exist on type '~lib/string/String'.

     contract.contractName = params.contractName.replace('0x00', '');
                                                 ~~~~~~~
 in src/mapping.ts(98,48)

✖ Failed to compile subgraph: Failed to compile data source mapping: Compile error
Error: Failed to compile data source mapping: Compile error
    at Compiler._compileDataSourceMapping (/Users/user1/projects/myproject/dapp.myproject.market/subgraph/node_modules/@graphprotocol/graph-cli/src/compiler.js:308:13)
    at /Users/user1/projects/myproject/dapp.myproject.market/subgraph/node_modules/@graphprotocol/graph-cli/src/compiler.js:184:20
    at updateInDeepMap (/Users/user1/projects/myproject/dapp.myproject.market/subgraph/node_modules/immutable/dist/immutable.js:1971:22)
    at updateInDeepMap (/Users/user1/projects/myproject/dapp.myproject.market/subgraph/node_modules/immutable/dist/immutable.js:1980:23)
    at updateInDeepMap (/Users/user1/projects/myproject/dapp.myproject.market/subgraph/node_modules/immutable/dist/immutable.js:1980:23)
    at Map.updateIn (/Users/user1/projects/myproject/dapp.myproject.market/subgraph/node_modules/immutable/dist/immutable.js:1278:26)
    at /Users/user1/projects/myproject/dapp.myproject.market/subgraph/node_modules/@graphprotocol/graph-cli/src/compiler.js:183:24
    at /Users/user1/projects/myproject/dapp.myproject.market/subgraph/node_modules/immutable/dist/immutable.js:3016:46
    at List.__iterate (/Users/user1/projects/myproject/dapp.myproject.market/subgraph/node_modules/immutable/dist/immutable.js:2206:13)
    at IndexedIterable.mappedSequence.__iterateUncached (/Users/user1/projects/myproject/dapp.myproject.market/subgraph/node_modules/immutable/dist/immutable.js:3015:23)
error Command failed with exit code 1.
```

package.json:
```
{
  "name": "myproject-graph",
  "version": "0.1.0",
  "scripts": {
    "create": "graph create myproject/myproject-graph --node https://api.thegraph.com/deploy/",
    "create-local": "graph create myproject/myproject-graph --node http://127.0.0.1:8020",
    "codegen": "graph codegen --debug --output-dir src/types/",
    "build": "graph build --debug",
    "deploy": "graph deploy myproject/myproject --debug --ipfs https://api.thegraph.com/ipfs/ --node https://api.thegraph.com/deploy/",
    "deploy-local": "graph deploy myproject/myproject-graph --debug --ipfs http://localhost:5001 --node http://127.0.0.1:8020"
  },
  "devDependencies": {
    "@graphprotocol/graph-cli": "^0.18.0",
    "@graphprotocol/graph-ts": "^0.18.0"
  },
  "dependencies": {
    "babel-polyfill": "^6.26.0",
    "babel-register": "^6.26.0",
    "truffle": "^5.0.4",
    "truffle-contract": "^4.0.5",
    "truffle-hdwallet-provider": "^1.0.4"
  }
}

```

**Comment by Jannis** [comment]
It's less a bug and more a missing feature. The latest version of AssemblyScript already supports methods such as `str.replace()`, but the version that we are using doesn't. For the moment, we are stuck to this version, as the AsssemblyScript memory allocation or layout changed and is now incompatible with our existing Rust <-> AssemblyScript glue code. That would need rewriting before we can bump to the latest AssemblyScript version.

**Comment by andrei-anisimov** [comment]
@Jannis I see, thanks for the clarification! The reason I'm doing the replace is because when I try to assign the value directly (without replace) I get the following error:
`Error while processing block stream for a subgraph: store error: invalid byte sequence for encoding "UTF8": 0x00`
The value doesn't seem to have '0x00' in it. Example value: `MRI-BTC-28D-20200501`. Any idea why this is happening?

**Comment by andrei-anisimov** [comment]
Looks like I was able to resolve it as follows. Still not sure why the null bytes get into the string. If you're already tracking it somewhere - feel free to close this one.
```
contract.contractName = params.contractName.substr(0, params.contractName.indexOf('\0'))
```
