### ISSUE TITLE
graph-cli won't install in docker

### ISSUE THREAD

**Issue by alexandruast** [graphprotocol/graph-cli#545]
## Problem

Starting with a fresh node:10 docker image, @graphprotocol/graph-cli will fail to install due to:
```
> ursa-optional@0.10.1 install /usr/local/lib/node_modules/@graphprotocol/graph-cli/node_modules/ursa-optional
> node rebuild.js

ursaNative bindings compilation fail. This is not an issue. Modules that depend on it will use fallbacks.
fs.js:114
    throw err;
    ^

Error: EACCES: permission denied, open './stdout.log'
    at Object.openSync (fs.js:443:3)
    at Object.writeFileSync (fs.js:1194:35)
    at Object.<anonymous> (/usr/local/lib/node_modules/@graphprotocol/graph-cli/node_modules/ursa-optional/rebuild.js:13:10)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
    at startup (internal/bootstrap/node.js:283:19)
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@~2.1.2 (node_modules/@graphprotocol/graph-cli/node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ursa-optional@0.10.1 install: `node rebuild.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the ursa-optional@0.10.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-08-28T06_49_02_684Z-debug.log
ERROR: Service 'cli' failed to build: The command '/bin/sh -c npm install -g @graphprotocol/graph-cli --registry https://testnet.thegraph.com/npm-registry/' returned a non-zero code: 1
```

## Dockerfile

```
FROM node:10

ARG NPM_REGISTRY_URL
ARG NPM_REGISTRY_USERNAME
ARG NPM_REGISTRY_PASSWORD
ARG NPM_REGISTRY_EMAIL

RUN npm install -g npm-cli-login

RUN npm-cli-login \
    -u "${NPM_REGISTRY_USERNAME}" \
    -p "${NPM_REGISTRY_PASSWORD}" \
    -e "${NPM_REGISTRY_EMAIL}" \
    -r "${NPM_REGISTRY_URL}"

RUN npm install -g @graphprotocol/indexer-cli --registry https://testnet.thegraph.com/npm-registry/

# FixMe: this fails -- Why?
# RUN npm install -g @graphprotocol/graph-cli --registry https://testnet.thegraph.com/npm-registry/
```

**Comment by nightfallen** [comment]
Found a fix for this last night. First make sure you're on the latest node version

```
sudo apt remove -y nodejs && sudo apt autoremove -y && \
curl -sL https://deb.nodesource.com/setup_14.x | \sudo -E bash - && \
sudo apt install -y nodejs && sudo npm install -g npm@latest
```

Then try to install graph-cli again.
----------------------------------------------------

If that fails still, try `sudo apt-get install libsecret-1-dev`

----------------------------------------------------

If that still doesn't work, you can try, according to [wiki](https://github.com/graphprotocol/mission-control-indexer/wiki/Troubleshooting#troubleshooting-npm-install-issues):

```
sudo npm set registry https://testnet.thegraph.com/npm-registry/
sudo npm login

sudo npm install -g \
 @graphprotocol/indexer-agent
```

Last chance is to force it with `-f`  <---   Actually this is how mine worked last night.

**Comment by alexandruast** [comment]
I am getting the same behavior with node:14 and libsecret-1-dev installed
Force install apparently does nothing

**Comment by nightfallen** [comment]
Try with sudo everything. Including login.

**Comment by latenthero** [comment]
Try this:
`npm install -g --unsafe-perm=true --allow-root @graphprotocol/graph-cli --registry https://testnet.thegraph.com/npm-registry/`

It's from troubleshooting guide:
https://github.com/graphprotocol/mission-control-indexer/wiki/Troubleshooting#troubleshooting-npm-install-issues

**Comment by nightfallen** [comment]
> Try this:
> `npm install -g --unsafe-perm=true --allow-root @graphprotocol/graph-cli --registry https://testnet.thegraph.com/npm-registry/`
> 
> It's from troubleshooting guide:
> https://github.com/graphprotocol/mission-control-indexer/wiki/Troubleshooting#troubleshooting-npm-install-issues

I linked the wiki in my post dude.

**Comment by alexandruast** [comment]
Solution without sudo hacks: [Dockerfile](https://gitlab.com/alexandruast/stake-systems/-/blob/master/graphprotocol/cli/Dockerfile)
