### ISSUE TITLE
Failed to install dependencies: Command failed: yarn

### ISSUE THREAD

**Issue by Levash0v** [graphprotocol/graph-cli#568]
Can not understand, when running command
**_graph init --from-example <GITHUB_USERNAME>/<SUBGRAPH_NAME> <DIRECTORY>_**
I get the result as in the log file below, what is the possible problem and solutions?

  Generate subgraph from ABI
  Write subgraph to directory
✔ Create subgraph scaffold
✔ Initialize subgraph repository
✖ Failed to install dependencies: Command failed: yarn
ERROR: There are no scenarios; must have at least one.

/usr/local/lib/node_modules/@graphprotocol/graph-cli/node_modules/binaryen/index.js:7
if(n){p=__dirname+"/";var ea,fa;a.read=function(c,e){var b=q(c);b||(ea||(ea=require("fs")),fa||(fa=require("path")),c=fa.normalize(c),b=ea.readFileSync(c));return e?b:b.toString()};a.readBinary=function(c){c=a.read(c,!0);c.buffer||(c=new Uint8Array(c));assert(c.buffer);return c};1<process.argv.length&&(a.thisProgram=process.argv[1].replace(/\\/g,"/"));a.arguments=process.argv.slice(2);process.on("uncaughtException",function(c){if(!(c instanceof ha))throw c;});process.on("unhandledRejection",u);a.quit=

Error: Command failed: yarn
ERROR: There are no scenarios; must have at least one.

    at ChildProcess.exithandler (child_process.js:294:12)
    at ChildProcess.emit (events.js:198:13)
    at maybeClose (internal/child_process.js:982:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)

**Comment by Levash0v** [comment]
In this case, when trying to overcome the problem, I tried to install in different ways, including installing several packages (yarn and npm), the problem was solved after adding settings to the github global settings (name and email)
