### ISSUE TITLE
Error storing access token with libsecret

### ISSUE THREAD

**Issue by 0xNL** [graphprotocol/graph-cli#569]
There was a problem while deploying (graph auth https://api.thegraph.com/deploy/ b14e43...)

**_Cannot store the access token because dependencies are missing. If you
are on Linux, try installing 'libsecret-1-dev' (Debian, Ubuntu etc.) or
'libsecret-devel' (RedHat, Fedora etc.) and reinstalling Graph CLI
afterwards._**

Installing the specified libraries does not solve the problem

**Comment by colourful-land** [comment]
I wish to add that installing the specified libraries and reinstalling Graph CLI does not solve the problem. And more specifically, on Ubuntu 20.04

Successfully installing dependency:

    $ sudo apt-get install libsecret-1-dev

Successfully uninstalled `graph-cli`

````
$ sudo npm uninstall -g @graphprotocol/graph-cli
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@~2.1.2 (node_modules/@graphprotocol/graph-cli/node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

removed 454 packages in 4.797s
````
Successfully installed it again:
````
$ sudo npm install -g @graphprotocol/graph-cli
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated peer-info@0.15.1: No longer supported for js-libp2p0.28.0 or later
npm WARN deprecated promisify-es6@1.0.3: Unmaintained
npm WARN deprecated multicodec@0.5.7: stable api reached
npm WARN deprecated libp2p-crypto-secp256k1@0.3.1: Included in libp2p-crypto, use it instead. https://github.com/libp2p/js-libp2p-crypto
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
/usr/local/bin/graph -> /usr/local/lib/node_modules/@graphprotocol/graph-cli/bin/graph

> ursa-optional@0.10.1 install /usr/local/lib/node_modules/@graphprotocol/graph-cli/node_modules/ursa-optional
> node rebuild.js
````

Still have the problem:
````
$ graph auth https://api.thegraph.com/deploy/ 1f5997fee622a06ef445d8668de292a873
Error: Error storing access token with libsecret (usually gnome-keyring or ksecretservice): Error: 

Cannot store the access token because dependencies are missing. If you
are on Linux, try installing 'libsecret-1-dev' (Debian, Ubuntu etc.) or
'libsecret-devel' (RedHat, Fedora etc.) and reinstalling Graph CLI
afterwards.

The original error was: Cannot find module '../build/Release/keytar.node'
      
    at saveAccessToken (/usr/local/lib/node_modules/@graphprotocol/graph-cli/src/command-helpers/auth.js:70:13)
    at Command.run (/usr/local/lib/node_modules/@graphprotocol/graph-cli/src/commands/auth.js:61:13)
    at Runtime.<anonymous> (/usr/local/lib/node_modules/@graphprotocol/graph-cli/node_modules/gluegun/build/runtime/run.js:118:58)
    at step (/usr/local/lib/node_modules/@graphprotocol/graph-cli/node_modules/gluegun/build/runtime/run.js:44:23)
    at Object.next (/usr/local/lib/node_modules/@graphprotocol/graph-cli/node_modules/gluegun/build/runtime/run.js:25:53)
    at fulfilled (/usr/local/lib/node_modules/@graphprotocol/graph-cli/node_modules/gluegun/build/runtime/run.js:16:58)
    at process._tickCallback (internal/process/next_tick.js:68:7)
````

**Comment by dpekar** [comment]
I'm getting a similar error but on Mac: 

```
graph auth https://api.thegraph.com/deploy/ 043b570ab1ef418924n4cc8a55e854c2
Error: Error storing access token in macOS Keychain: Error: 

Cannot store the access token because dependencies are missing. If you
are on Linux, try installing 'libsecret-1-dev' (Debian, Ubuntu etc.) or
'libsecret-devel' (RedHat, Fedora etc.) and reinstalling Graph CLI
afterwards.

The original error was: Module did not self-register: '~/.config/yarn/global/node_modules/keytar/build/Release/keytar.node'.
      
    at saveAccessToken (~/.config/yarn/global/node_modules/@graphprotocol/graph-cli/src/command-helpers/auth.js:68:13)
    at Command.run (~/.config/yarn/global/node_modules/@graphprotocol/graph-cli/src/commands/auth.js:61:13)
    at Runtime.<anonymous> (~/.config/yarn/global/node_modules/gluegun/build/runtime/run.js:118:58)
    at step (~/.config/yarn/global/node_modules/gluegun/build/runtime/run.js:44:23)
    at Object.next (~/.config/yarn/global/node_modules/gluegun/build/runtime/run.js:25:53)
    at fulfilled (~/.config/yarn/global/node_modules/gluegun/build/runtime/run.js:16:58)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)

```

**Comment by dpekar** [comment]
For others hitting this issue, you can easily work around it by supplying your access token as an option to your deploy deploy: 
`graph deploy --debug --ipfs https://api.thegraph.com/ipfs/ --node https://api.thegraph.com/deploy/ --access-token <YOUR KEY>`

**Comment by crazyrabbitLTC** [comment]
Hey folks, if this helps- I was hitting this problem in node 12.18.2: my previous AUTH no longer worked, doing a new AUTH didn't work either,  but then I switched to 11.15.0 (which I had been using previously) and it worked.

**Comment by crazyrabbitLTC** [comment]
I've hit this bug again on a brand new install (wiping hard drive) of OSX Big Sur. Tried switching to node v11.15.0 as I had done before but no luck.

**Comment by Jannis** [comment]
`node-keytar`, the package that we're using for storing access tokens securely in the user's system keyring, has been the bane of my existence ever since we introduced it. I would love to find a good replacement because it only seems to work for a fraction of the users out there.

The good news is: You can work around it by passing the access token straight to graph CLI:

```sh
graph deploy ... --access-token ...
```

**Comment by MagikBOZO** [comment]
> For others hitting this issue, you can easily work around it by supplying the access token as an option to your deploy:
> `graph deploy --debug --ipfs https://api.thegraph.com/ipfs/ --node https://api.thegraph.com/deploy/ --access-token <YOUR KEY>`

thanks buddy

**Comment by schmidsi** [comment]
@Jannis What about ditching keytar completely and migrate to a different auth flow: Either via `GRAPH_ACCESS_TOKEN` env-var with support for [.env](https://www.npmjs.com/package/dotenv) files or via command line argument as described above.

It would make also make the use case easier, where a developer works on subgraphs with different accounts: The .env file would be in each project root.

**Comment by Jannis** [comment]
Yeah, I agree we should ditch node-keytar. It's a pain. I _would_ like to be able to store access tokens in a secure way though. Perhaps it's not so important but perhaps there's an alternative that we could use?

**Comment by schmidsi** [comment]
As far as I know, env-vars can be quite secure if handled properly.

**Comment by devinaconley** [comment]
If anyone else is still hitting this, it was due to a change in node version for me. Flushing all npm packages and reinstalling with the newer version fixed it.
