### ISSUE TITLE
Cannot import assemblyscript module

### ISSUE THREAD

**Issue by Remscar** [graphprotocol/graph-cli#663]
I've been trying to import the `assemblyscript-regex` npm package which is an assembly script library that provides RegEx. (https://www.npmjs.com/package/assemblyscript-regex)

I import the package like:

```
import { Match, RegExp } from "assemblyscript-regex";
```

and when i try to run `graph build` i get the following error:

```
× Failed to compile subgraph: Failed to compile data source mapping: Import file '~lib/assemblyscript-regex.ts' not found.     
Error: Failed to compile data source mapping: Import file '~lib/assemblyscript-regex.ts' not found.
    at Compiler._compileDataSourceMapping (E:\dOrg\xxx-subgraph\node_modules\@graphprotocol\graph-cli\src\compiler.js:312:13)  
    at E:\dOrg\xxx-subgraph\node_modules\@graphprotocol\graph-cli\src\compiler.js:206:20
    at updateInDeepMap (E:\dOrg\xxx-subgraph\node_modules\immutable\dist\immutable.js:1971:22)
    at updateInDeepMap (E:\dOrg\xxx-subgraph\node_modules\immutable\dist\immutable.js:1980:23)
    at updateInDeepMap (E:\dOrg\xxx-subgraph\node_modules\immutable\dist\immutable.js:1980:23)
    at Map.updateIn (E:\dOrg\xxx-subgraph\node_modules\immutable\dist\immutable.js:1278:26)
    at E:\dOrg\xxx-subgraph\node_modules\@graphprotocol\graph-cli\src\compiler.js:205:24
    at E:\dOrg\xxx-subgraph\node_modules\immutable\dist\immutable.js:3016:46
    at List.__iterate (E:\dOrg\zns-subgraph\node_modules\immutable\dist\immutable.js:2206:13)
    at IndexedIterable.mappedSequence.__iterateUncached (E:\dOrg\xxx-subgraph\node_modules\immutable\dist\immutable.js:3015:23)
```

I tried to just copy/paste the assembly script code into my `src` folder and use it through that but also ran into a number of compiler problems (such as 'operation not supported')

My understanding was that you could import other assemblyscript modules into subgraph modules. What am I doing wrong, or is this package just incompatible?

**Comment by leoyvens** [comment]
We are working on upgrading our AS version so we can be compatible with the ecosystem.

**Comment by dewf** [comment]
@leoyvens Can you tell us how big of a change this would be, thus how far on the horizon it might be? Like @Remscar, I need regex support and would also like to import the bulk of my own code as a library (because it's shared with another project).

Would this be something worth looking into for an 'amateur' (a reasonably competent developer, but totally unfamiliar with the codebase)? How far could somebody get just bumping the AS version and focusing on broken tests?

Thanks!

**Comment by schmidsi** [comment]
@dewf No need to invest too much time into this. There is already a [open pull-request](https://github.com/graphprotocol/graph-cli/pull/690) where we are working on at the moment. That said, it will probably take some more weeks because it also is dependent on changes in the graph-node.

**Comment by dewf** [comment]
@azf20 thanks for the heads-up. I was actually just waiting for the full release but since you asked nicely I decided to try to work with the alpha. Unfortunately I'm blocked on the same `@derivedFrom` field [issue](https://gist.github.com/otaviopace/8406cb39644d2e7678570d1e7f50dac4#gistcomment-3878941) as the other person testing it, so I will try back in a week or two (my project has been on the backburner for awhile now so unfortunately I can't devote too much focus - so please don't give this any extra emphasis on my account)

**Comment by otaviopace** [comment]
The `derivedFrom` issue is a simple fix, I'll focus on it next week 🙂 
Once it's merged and released I'll ping you here!

**Comment by otaviopace** [comment]
I'll check this out later, but my guess is that this regex library only supports later versions of the AssemblyScript compiler.

The version you're using of `graph-cli` and `graph-ts` still use version `0.6` of AssemblyScript. 

The good news is that we have updated it recently, but it's still in alpha version. We have a migration guid that's still on a Gist while we don't publish on the official docs: https://gist.github.com/otaviopace/8406cb39644d2e7678570d1e7f50dac4.

**Comment by cauta** [comment]
can we use as external library now? i want to call external http request by as-fetch

**Comment by otaviopace** [comment]
The new version of AssemblyScript is finally supported by the new version of the `graph-cli` and `graph-node`  🎉 🎊 

@Remscar @nickadamson @dewf if you folks can try it out, here's the [migration guide](https://thegraph.com/docs/developer/assemblyscript-migration-guide) 🙂

@cauta unfortunately you can't use `as-fetch`. Allowing HTTP requests in the subgraph would result to non-deterministic indexing (different results depending on **where** and **when** the request was done).
