### ISSUE TITLE
Build issue: ERROR TS1110: Type expected when event has a param named yield

### ISSUE THREAD

**Issue by iRhonin** [graphprotocol/graph-cli#883]
I was trying to create a subgraph for a contract but on the build, I get `ERROR TS1110: Type expected`. 

When I rename the `yield` word to something else, there is no error!

Reproduce with: 

```
graph init --product hosted-service --from-contract 0xc6764e58b36e26b08Fd1d2AeD4538c02171fA872 GITHUB_USER/SUBGRAPH_NAME

cd SUBGRAPH_NAME
 
graph codegen

graph build
```

Log: 

```bash
yarn run v1.22.18
$ graph build
  Skip migration: Bump mapping apiVersion from 0.0.1 to 0.0.2
  Skip migration: Bump mapping apiVersion from 0.0.2 to 0.0.3
  Skip migration: Bump mapping apiVersion from 0.0.3 to 0.0.4
  Skip migration: Bump mapping apiVersion from 0.0.4 to 0.0.5
  Skip migration: Bump mapping specVersion from 0.0.1 to 0.0.2
✔ Apply migrations
✔ Load subgraph from subgraph.yaml
  Compile data source: Contract => build/Contract/Contract.wasm
⠋ Compile subgraphERROR TS1110: Type expected.

   get yield(): BigInt {
   ~~~
 in generated/Contract/Contract.ts(44,3)

ERROR TS1110: Type expected.

   get yield(): BigInt {
   ~~~
 in generated/Contract/Contract.ts(154,3)

✖ Failed to compile subgraph: Failed to compile data source mapping: 2 parse error(s)
Error: Failed to compile data source mapping: 2 parse error(s)
    at Compiler._compileDataSourceMapping (/home/rhonin2/workshop/graph/SUBGRAPH_NAME/node_modules/@graphprotocol/graph-cli/src/compiler/index.js:307:13)
    at /home/rhonin2/workshop/graph/SUBGRAPH_NAME/node_modules/@graphprotocol/graph-cli/src/compiler/index.js:216:20
    at updateInDeepMap (/home/rhonin2/workshop/graph/SUBGRAPH_NAME/node_modules/immutable/dist/immutable.js:1971:22)
    at updateInDeepMap (/home/rhonin2/workshop/graph/SUBGRAPH_NAME/node_modules/immutable/dist/immutable.js:1980:23)
    at updateInDeepMap (/home/rhonin2/workshop/graph/SUBGRAPH_NAME/node_modules/immutable/dist/immutable.js:1980:23)
    at Map.updateIn (/home/rhonin2/workshop/graph/SUBGRAPH_NAME/node_modules/immutable/dist/immutable.js:1278:26)
    at /home/rhonin2/workshop/graph/SUBGRAPH_NAME/node_modules/@graphprotocol/graph-cli/src/compiler/index.js:215:24
    at /home/rhonin2/workshop/graph/SUBGRAPH_NAME/node_modules/immutable/dist/immutable.js:3016:46
    at List.__iterate (/home/rhonin2/workshop/graph/SUBGRAPH_NAME/node_modules/immutable/dist/immutable.js:2206:13)
    at IndexedIterable.mappedSequence.__iterateUncached (/home/rhonin2/workshop/graph/SUBGRAPH_NAME/node_modules/immutable/dist/immutable.js:3015:23)
UNCAUGHT EXCEPTION: Error: The AssemblyScript compiler crashed when compiling this file: 'src/mapping.ts'
Suggestion: try to comment the whole file and uncomment it little by little while re-running the graph-cli until you isolate the line where the problem happens.
Also, please contact us so we can make the CLI better by handling errors like this. You can reach out in any of these links:
- Discord channel: https://discord.gg/eM8CA6WA9r
- Github issues: https://github.com/graphprotocol/graph-cli/issues
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by dimitrovmaksim** [comment]
Maybe `yield` is a reserved word

**Comment by iRhonin** [comment]
> Maybe `yield` is a reserved keyword

I am thinking the same, do you have any idea on checking that? Sorry I don't know much about Js/Ts debugging.

**Comment by dimitrovmaksim** [comment]
`yield` is a reserved keyword in strict mode in TS, maybe in AssemblyScript too, although i can't find any info on that.

**Comment by iRhonin** [comment]
Tnx for clarification.

For anybody facing same issue, I renamed `yield` in the ABI to something else like `_yield` as a workaround.
