### ISSUE TITLE
TS2322: Type '~lib/@graphprotocol/graph-ts/common/collections/Bytes' is not assignable to type '~lib/string/String'.

### ISSUE THREAD

**Issue by soniajoseph** [graphprotocol/graph-cli#933]
Hi, when I enter the command `graph build`, I get the following error in my `src/token.ts` file:

```

✔ Apply migrations
✔ Load subgraph from subgraph.yaml
  Compile data source: Token => build/Token/Token.wasm
⠋ Compile subgraphERROR TS2322: Type '~lib/@graphprotocol/graph-ts/common/collections/Bytes' is not assignable to type '~lib/string/String'.

   entity.indexedTokenIPFSPath = event.params.indexedTokenIPFSPath
                                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 in src/token.ts(70,33)

ERROR TS2322: Type '~lib/@graphprotocol/graph-ts/common/collections/Bytes' is not assignable to type '~lib/string/String'.

   entity.indexedTokenIPFSPath = event.params.indexedTokenIPFSPath
                                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 in src/token.ts(174,33)

✖ Failed to compile subgraph: Failed to compile data source mapping: 2 compile error(s)
Error: Failed to compile data source mapping: 2 compile error(s)
    at Compiler._compileDataSourceMapping (/usr/local/lib/node_modules/@graphprotocol/graph-cli/src/compiler/index.js:307:13)
    at /usr/local/lib/node_modules/@graphprotocol/graph-cli/src/compiler/index.js:216:20
    at updateInDeepMap (/usr/local/lib/node_modules/@graphprotocol/graph-cli/node_modules/immutable/dist/immutable.js:1971:22)
    at updateInDeepMap (/usr/local/lib/node_modules/@graphprotocol/graph-cli/node_modules/immutable/dist/immutable.js:1980:23)
    at updateInDeepMap (/usr/local/lib/node_modules/@graphprotocol/graph-cli/node_modules/immutable/dist/immutable.js:1980:23)
    at Map.updateIn (/usr/local/lib/node_modules/@graphprotocol/graph-cli/node_modules/immutable/dist/immutable.js:1278:26)
    at /usr/local/lib/node_modules/@graphprotocol/graph-cli/src/compiler/index.js:215:24
    at /usr/local/lib/node_modules/@graphprotocol/graph-cli/node_modules/immutable/dist/immutable.js:3016:46
    at List.__iterate (/usr/local/lib/node_modules/@graphprotocol/graph-cli/node_modules/immutable/dist/immutable.js:2206:13)
    at mappedSequence.__iterateUncached (/usr/local/lib/node_modules/@graphprotocol/graph-cli/node_modules/immutable/dist/immutable.js:3015:23)
UNCAUGHT EXCEPTION: Error: The AssemblyScript compiler crashed when compiling this file: 'src/token.ts'
Suggestion: try to comment the whole file and uncomment it little by little while re-running the graph-cli until you isolate the line where the problem happens.
Also, please contact us so we can make the CLI better by handling errors like this. You can reach out in any of these links:
- Discord channel: https://discord.gg/eM8CA6WA9r
- Github issues: https://github.com/graphprotocol/graph-cli/issues

```

Any ideas? Thanks!

**Comment by azf20** [comment]
Hi!  That suggests that the type of the event parameter is different to the type of the field on the entity. You should make them the same, or transform the event parameter accordingly. If you are still having issues, Discord is the best place to get help (in #subgraph-development)
Discord channel: https://discord.gg/eM8CA6WA9r
