### ISSUE TITLE
graph init error 

### ISSUE THREAD

**Issue by LonYui** [graphprotocol/graph-cli#937]
brief: shoud not error this. from input:contract name no rgx check 

```
✔ Contract Name · Young Male Florist
———
  Generate subgraph
✖ Failed to create subgraph scaffold: ',' expected. (3:18)
  1 | 
  2 |   import { BigInt } from '@graphprotocol/graph-ts'
> 3 |   import { Young Male Florist, Approval,ApprovalForAll,OwnershipTransferred,Transfer }
    |                  ^
  4 |     from '../generated/Young Male Florist/Young Male Florist'
  5 |   import { ExampleEntity } from '../generated/schema'
  6 | 
/Users/tsung-han/.nvm/versions/node/v16.13.0/lib/node_modules/@graphprotocol/graph-cli/node_modules/gluegun/build/index.js:13
    throw up;
    ^

SyntaxError: ',' expected. (3:18)
  1 | 
  2 |   import { BigInt } from '@graphprotocol/graph-ts'
> 3 |   import { Young Male Florist, Approval,ApprovalForAll,OwnershipTransferred,Transfer }
    |                  ^
  4 |     from '../generated/Young Male Florist/Young Male Florist'
  5 |   import { ExampleEntity } from '../generated/schema'
  6 | 
    at t (/Users/tsung-han/.nvm/versions/node/v16.13.0/lib/node_modules/@graphprotocol/graph-cli/node_modules/prettier/parser-typescript.js:1:285)
    at Object.parse (/Users/tsung-han/.nvm/versions/node/v16.13.0/lib/node_modules/@graphprotocol/graph-cli/node_modules/prettier/parser-typescript.js:14:180461)
    at Object.parse (/Users/tsung-han/.nvm/versions/node/v16.13.0/lib/node_modules/@graphprotocol/graph-cli/node_modules/prettier/index.js:9739:19)
    at coreFormat (/Users/tsung-han/.nvm/versions/node/v16.13.0/lib/node_modules/@graphprotocol/graph-cli/node_modules/prettier/index.js:13252:23)
    at format (/Users/tsung-han/.nvm/versions/node/v16.13.0/lib/node_modules/@graphprotocol/graph-cli/node_modules/prettier/index.js:13510:73)
    at formatWithCursor (/Users/tsung-han/.nvm/versions/node/v16.13.0/lib/node_modules/@graphprotocol/graph-cli/node_modules/prettier/index.js:13526:12)
    at /Users/tsung-han/.nvm/versions/node/v16.13.0/lib/node_modules/@graphprotocol/graph-cli/node_modules/prettier/index.js:44207:15
    at Object.format (/Users/tsung-han/.nvm/versions/node/v16.13.0/lib/node_modules/@graphprotocol/graph-cli/node_modules/prettier/index.js:44226:12)
    at Scaffold.generateMapping (/Users/tsung-han/.nvm/versions/node/v16.13.0/lib/node_modules/@graphprotocol/graph-cli/src/scaffold/index.js:121:21)
    at Scaffold.generate (/Users/tsung-han/.nvm/versions/node/v16.13.0/lib/node_modules/@graphprotocol/graph-cli/src/scaffold/index.js:157:67) {
  loc: { start: { line: 3, column: 18 } },
  codeFrame: '\x1B[0m \x1B[90m 1 | \x1B[39m\x1B[0m\n' +
    "\x1B[0m \x1B[90m 2 | \x1B[39m  \x1B[36mimport\x1B[39m { \x1B[33mBigInt\x1B[39m } from \x1B[32m'@graphprotocol/graph-ts'\x1B[39m\x1B[0m\n" +
    '\x1B[0m\x1B[31m\x1B[1m>\x1B[22m\x1B[39m\x1B[90m 3 | \x1B[39m  \x1B[36mimport\x1B[39m { \x1B[33mYoung\x1B[39m \x1B[33mMale\x1B[39m \x1B[33mFlorist\x1B[39m\x1B[33m,\x1B[39m \x1B[33mApproval\x1B[39m\x1B[33m,\x1B[39m\x1B[33mApprovalForAll\x1B[39m\x1B[33m,\x1B[39m\x1B[33mOwnershipTransferred\x1B[39m\x1B[33m,\x1B[39m\x1B[33mTransfer\x1B[39m }\x1B[0m\n' +
    '\x1B[0m \x1B[90m   | \x1B[39m                 \x1B[31m\x1B[1m^\x1B[22m\x1B[39m\x1B[0m\n' +
    "\x1B[0m \x1B[90m 4 | \x1B[39m    from \x1B[32m'../generated/Young Male Florist/Young Male Florist'\x1B[39m\x1B[0m\n" +
    "\x1B[0m \x1B[90m 5 | \x1B[39m  \x1B[36mimport\x1B[39m { \x1B[33mExampleEntity\x1B[39m } from \x1B[32m'../generated/schema'\x1B[39m\x1B[0m\n" +
    '\x1B[0m \x1B[90m 6 | \x1B[39m\x1B[0m'
}
```

**Comment by ywk248248** [comment]
You helped me out debugging...Thanks bro
