### ISSUE TITLE
Can't use the CLI.

### ISSUE THREAD

**Issue by saeta-eth** [graphprotocol/graph-cli#948]
Hi there,

I have installed the graph cli using npm and I can't initialize a project because I'm getting this error

```
graph init --studio example
/usr/local/lib/node_modules/@graphprotocol/graph-cli/node_modules/gluegun/build/index.js:13
    throw up;
    ^

Error: Timed out waiting for sync-rpc server to start (it should respond with "pong" when sent "ping"):

node:events:498
      throw er; // Unhandled 'error' event
      ^

Error: connect ETIMEDOUT 127.0.0.1:58452
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1157:16)
Emitted 'error' event on Socket instance at:
    at emitErrorNT (node:internal/streams/destroy:157:8)
    at emitErrorCloseNT (node:internal/streams/destroy:122:3)
    at processTicksAndRejections (node:internal/process/task_queues:83:21) {
  errno: -60,
  code: 'ETIMEDOUT',
  syscall: 'connect',
  address: '127.0.0.1',
  port: 58452
}


    at waitForAlive (/usr/local/lib/node_modules/@graphprotocol/graph-cli/node_modules/sync-rpc/lib/index.js:85:11)
    at start (/usr/local/lib/node_modules/@graphprotocol/graph-cli/node_modules/sync-rpc/lib/index.js:41:3)
    at sendMessage (/usr/local/lib/node_modules/@graphprotocol/graph-cli/node_modules/sync-rpc/lib/index.js:133:17)
    at createClient (/usr/local/lib/node_modules/@graphprotocol/graph-cli/node_modules/sync-rpc/lib/index.js:173:27)
    at Object.<anonymous> (/usr/local/lib/node_modules/@graphprotocol/graph-cli/node_modules/sync-request/lib/index.js:16:14)
    at Module._compile (node:internal/modules/cjs/loader:1103:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1155:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
```

Not sure if I'm doing something wrong or what, any advice?

**Comment by saeta-eth** [comment]
I found what the issue was, I disconnected my VPN and now it works.
